apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elk
spec:
  version: 7.16.3
  nodeSets:
    - name: default
      count: 3  
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
        cluster.routing.allocation.awareness.attributes: zone
        cluster.routing.allocation.disk.threshold_enabled: true
        cluster.routing.allocation.disk.watermark.low: 85%
        cluster.routing.allocation.disk.watermark.high: 90%
        cluster.routing.allocation.disk.watermark.flood_stage: 95%
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "2Gi"  
                  cpu: "1"
                limits:
                  memory: "4Gi"
                  cpu: "2"
  http:
    service:
      spec:
        type: NodePort
