global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ping-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['ping-app-service.ping-app.svc.cluster.local:80']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
