apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-app-deployment
  namespace: ping-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ping-app
  template:
    metadata:
      labels:
        app: ping-app
    spec:
      containers:
      - name: ping-app-container
        image: ping-app-img:27052024.1
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-uri-secret
              key: MONGO_URI
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.16.3
        volumeMounts:
        - name: config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        - name: logs
          mountPath: /var/log/app
      volumes:
      - name: config
        configMap:
          name: filebeat-config
      - name: logs
        emptyDir: {}