apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ping-app-hpa
  namespace: ping-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ping-app-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 75
