apiVersion: v1
kind: Service
metadata:
  name: ping-app-service
  namespace: ping-app
spec:
  selector:
    app: ping-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
